### ISSUE TITLE
How can I get client_id?

### ISSUE THREAD

**Issue by frgmt** [adswerve/GA4-Measurement-Protocol-Python#30]
How can I get client_id? Please give me more detail.
I'm facing to get 204 status.

- Which API should I use?
- Do I have to make client_id every time?

**Comment by sk0g** [comment]
Did you end up figuring this issue out? Not entirely sure the documentation in this library is correct.

**Comment by frgmt** [comment]
![ga4](https://user-images.githubusercontent.com/43658304/150114998-9dcd8180-233e-4380-8ac7-ccbd2047c50e.png)

@sk0g Yes, I did. It was just same as the documentation. Please look at above.
https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid?hl=en

**Comment by sk0g** [comment]
Ah figured that might have been the case, but pretty sure at that point any random string would work. See my issue posted, but I think the documentation is misleading, and those OAuth IDs are completely unrelated to anything here. AFAIK Google Ads is completely separate to that, as you create GA specific credentials to use, and can't use those.

https://github.com/adswerve/GA4-Measurement-Protocol-Python/issues/31
